name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    name: Test (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck jq mpv curl fzf chafa yt-dlp

    - name: Install xh (non-interactive)
      run: |
        mkdir -p ~/.local/bin
        curl -sL https://github.com/ducaale/xh/releases/download/v0.24.1/xh-v0.24.1-x86_64-unknown-linux-musl.tar.gz \
        | tar xz --strip-components=1 -C ~/.local/bin xh-v0.24.1-x86_64-unknown-linux-musl/xh
        chmod +x ~/.local/bin/xh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"


    - name: Lint with ShellCheck
      run: shellcheck ytsurf.sh

    - name: Run Sanity Checks
      run: |
        # Test that the script runs with the --history flag (non-interactive)
        ./ytsurf.sh -V

        # Test that the script exits with an error on invalid input
        # We expect this to fail, so we invert the exit code with !
        ! ./ytsurf.sh --limit "not-a-number"

  test-windows:
    name: Test (windows-latest)
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies via Scoop
      shell: powershell
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        irm get.scoop.sh | iex
        scoop install main/shellcheck main/jq main/fzf main/curl

    - name: Add Scoop to PATH
      shell: powershell
      run: echo "$env:USERPROFILE\scoop\shims" >> $env:GITHUB_PATH

    - name: Lint with ShellCheck
      run: shellcheck ytsurf.sh

    - name: Run Sanity Checks
      run: |
        ./ytsurf.sh -V
        ! ./ytsurf.sh --limit "not-a-number"
        ! ./ytsurf.sh --rofi

    name: Test (macos-latest)
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew update
        brew install shellcheck jq mpv curl fzf chafa yt-dlp xh

    - name: Lint with ShellCheck
      run: shellcheck ytsurf.sh

    - name: Run Sanity Checks
      run: |
        # Test that the script runs with the --history flag (non-interactive)
        ./ytsurf.sh -V

        # Test that the script exits with an error on invalid input
        # We expect this to fail, so we invert the exit code with !
        ! ./ytsurf.sh --limit "not-a-number"
